### ISSUE TITLE
Registre d'usuaris

### ISSUE THREAD

**Issue by fansubscat** [Ereza/Fansubs.cat#2]
- Permetre registre, inici de sessió i tancament de sessió.
- Fer el seguiment de visualitzacions/sèries preferides
- Desar la configuració a l'usuari, no a les galetes.

**Comment by guillezcurra** [comment]
Hola, sóc usuari de la web i he vist, revisant el repositori, que sí que hi ha una taula de la BD on es declaren els paràmetres dels usuaris, hi ha cap motiu pel qual no s'ha implementat això a la pàgina web? Puc ajudar a fer-ho? Sempre em passa que miro una sèrie i després hi entro amb un altre ordinador però no recordo per quin capítol vaig, estaria bé tenir un usuari i poder fer una mena de "preferits".

**Comment by fansubscat** [comment]
Bon dia! Actualment hi estem treballant, juntament amb un redisseny complet dels portals amb un estil més modern i coherent. La taula que has vist a la base de dades es va crear fa temps ja amb aquesta idea en ment, però el codi no la fa servir per a res... encara. Esperem tenir-ho enllestit aviat, i efectivament, la idea és que es pugui fer el que tu dius, una llista de sèries preferides i que se sincronitzi l'estat de tot el que has vist.

**Comment by fansubscat** [comment]
Implementat a la futura versió v5.

**Comment by guillezcurra** [comment]
L'enhorabona! Les noves funcionalitats van molt bé!

**Comment by fansubscat** [comment]
Moltes gràcies!! Ha costat, però ja tocava!
